### ISSUE TITLE
Hub crashes when keycloak crashes after startup.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#272]
It has been reported that the hub will crash-loop after keycloak (or the node it's on) has crashed.
Investigate the crash-loop. Hopefully this can be reproduced by scaling-down keycloak after the hub has started.

When keycloak unavailable, API requests should result in a 503.

**Comment by mansam** [comment]
When the Hub starts, it attempts to reconcile its Keycloak realm. It retries this repeatedly to cope with the Hub possibly coming up before Keycloak is ready. Prior to #278, it would retry for three minutes and then fail, causing the container to restart. #278 causes it to retry forever.

Once the Hub is running, it only needs to talk to the Keycloak API to cache the certificates it will use to verify tokens. After that, it does not need to talk to the Keycloak API. Keycloak going down will not cause the Hub to crash at this point. If the Keycloak API is down and the Hub does not have the certificates cached, decoding the token will fail and the Hub will return a NotAuthenticated error. The Hub can't tell whether decoding failed because Keycloak is down, the certificates don't match, or some other reason, so we can't easily choose to report a 503.
